### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lanmasco** [poanchen/poanchen.github.io#20]
how to repair this code

30	4	C:\Program Files (x86)\Dev-Cpp\MinGW64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++\bits\c++0x_warning.h	[Error] expected constructor, destructor, or type conversion before '(' token

#ifndef _CXX0X_WARNING_H
#define _CXX0X_WARNING_H 1
#if __cplusplus < 201103L
#error This file requires compiler and library support for the
ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
#endif

#endif

**Comment by poanchen** [comment]
Hey Ian,

Sorry for the late reply. This repo is designed to create issue against the blog itself. For example, typo in the blog post or anything that the user recommended or they had issue with the site. This is not the place for asking for help regarding your code. Please leave a disqus comments in the blog post so that me or others can help. Closing this issue.
